dist: bionic

language: cpp

before_install:
  - curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  - sudo apt-get -qq update
  - sudo apt-get install -y mono-mcs crystal

install: make clean build

script: make test
